/* Include the controller definition */
#include "$CTRL_NAME$.h"
/* Function definitions for XML parsing */
#include <argos3/core/utility/configuration/argos_configuration.h>
/* 2D vector definition */
#include <argos3/core/utility/math/vector2.h>

#include "$MDL_NAME$.h"            // Model's header file
#include "rtwtypes.h"		       // MATLAB types


/****************************************/
/****************************************/

C$CTRL_NAME$::C$CTRL_NAME$() : m_mlObj($MDL_NAME$ModelClass()) { }

/****************************************/
/****************************************/

void C$CTRL_NAME$::Init(TConfigurationNode& t_node) {
   m_mlObj.initialize(this); // Autogenerated Initialize Method, modified to accept the actuator 
}

/****************************************/
/****************************************/

void C$CTRL_NAME$::ControlStep() {
   m_mlObj.step();  // Autogenerated Step Method
}

/****************************************/
/****************************************/


/*
 * This statement notifies ARGoS of the existence of the controller.
 * It binds the class passed as first argument to the string passed as
 * second argument.
 * The string is then usable in the configuration file to refer to this
 * controller.
 * When ARGoS reads that string in the configuration file, it knows which
 * controller class to instantiate.
 * See also the configuration files for an example of how this is used.
 */
REGISTER_CONTROLLER(C$CTRL_NAME$, "$CTRL_NAME$_controller")
